### ISSUE TITLE
Umbrella issue for MIT/Apache-2.0 relicensing

### ISSUE THREAD

**Issue by hobofan** [autumnai/leaf#39]
Recently multiple issues were created suggesting relicensing of multiple projects related to Leaf to a dual MIT/Apache-2.0 license.

@MichaelHirn and I discussed the issue and are both in favor of relicensing the concerned projects, however we don't inted to include license headers for the Apache-2.0 license in every file.

List of the issues for reference, and status of signatures collected:
- [x] https://github.com/autumnai/leaf/issues/38
- [x] https://github.com/autumnai/cuticula/issues/20
- [x] https://github.com/autumnai/collenchyma/issues/34
- [x] https://github.com/autumnai/collenchyma-blas/issues/4
- [x] https://github.com/autumnai/collenchyma-nn/issues/10
- [x] https://github.com/autumnai/rust-cudnn/issues/10

We will also have to ask permission to relicense for any contributors of outstanding PRs before merging them.

**Comment by hobofan** [comment]
@cmr : It seems https://github.com/autumnai/collenchyma and https://github.com/autumnai/rust-cudnn didn't get a automatic issue. Could you poke your script to do that please? :)

**Comment by cmr** [comment]
Sure thing!

On January 14, 2016 6:27:47 AM EST, Maximilian Goisser <notifications@github.com> wrote:
>@cmr : It seems https://github.com/autumnai/collenchyma and
>https://github.com/autumnai/rust-cudnn didn't get a automatic issue.
>Could you poke your script to do that please? :)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/autumnai/leaf/issues/39#issuecomment-171617909

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by hobofan** [comment]
Since (from what I've heard/read), @cmr isn't allowed to continue the initative, we'll have make the relicensing changes by hand.  
All contributors have agreed to the relicensing, except for @kschmit90 who hasn't responded. Since his contribution consisted of fixing grammar mistakes, we don't consider it "creative work" (even though the contribution is greatly appreciated) and will relicense Leaf without his agreement.

List of the issues for reference, and status of changing the repository:
- [ ] https://github.com/autumnai/leaf/issues/38
- [ ] https://github.com/autumnai/cuticula/issues/20
- [ ] https://github.com/autumnai/collenchyma/issues/34
- [ ] https://github.com/autumnai/collenchyma-blas/issues/4
- [ ] https://github.com/autumnai/collenchyma-nn/issues/10
- [ ] https://github.com/autumnai/rust-cudnn/issues/10
